const plantData = [
    {
        "Nome": "Helicônia Papagaio",
        "Nome Científico": "Heliconia psittacorum",
        "Descrição": "Planta tropical de floração exuberante, com flores em tons de laranja, vermelho e amarelo. Perfeita para o clima de Ilhéus.",
        "Altura": "1-2 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Alta",
        "Crescimento": "Rápido",
        "Solo Ideal": "Rico em matéria orgânica, bem drenado",
        "Floração": "Ano todo",
        "Cores": "Laranja; Vermelho; Amarelo",
        "Tags": "Herbácea; Fácil de Cuidar; Tropical; Tolerante à Maresia; Floração Ornamental; Atrai Beija-flores"
    },
    {
        "Nome": "Palmeira-leque",
        "Nome Científico": "Licuala grandis",
        "Descrição": "Palmeira de beleza escultural, com folhas grandes, redondas e plissadas. Crescimento lento, ideal para vasos ou jardins de sombra.",
        "Altura": "2-3 m",
        "Luz Solar": "Meia Sombra",
        "Necessidade de Água": "Média",
        "Crescimento": "Lento",
        "Solo Ideal": "Rico em matéria orgânica, bem drenado",
        "Floração": "Verão",
        "Cores": "Verde; Creme",
        "Tags": "Palmeira; Cuidado Moderado; Tropical; Folhagem Ornamental; Ideal para Vasos; Tolerante à Sombra"
    },
    {
        "Nome": "Costela-de-adão",
        "Nome Científico": "Monstera deliciosa",
        "Descrição": "Planta icônica com folhas grandes e recortadas. Traz um visual 'urban jungle' instantâneo para dentro de casa ou áreas sombreadas.",
        "Altura": "3-5 m (apoiada)",
        "Luz Solar": "Sombra",
        "Necessidade de Água": "Média",
        "Crescimento": "Moderado",
        "Solo Ideal": "Rico em matéria orgânica, bem drenado",
        "Floração": "Verão (raro em interiores)",
        "Cores": "Verde; Branco",
        "Tags": "Trepadeira; Fácil de Cuidar; Tropical; Folhagem Ornamental; Ideal para Vasos; Tolerante à Sombra; Purifica o Ar"
    },
    {
        "Nome": "Ixora-vermelha",
        "Nome Científico": "Ixora coccinea",
        "Descrição": "Arbusto popular em Ilhéus, produz cachos densos de flores vermelhas vibrantes o ano todo. Excelente para cercas vivas ou como destaque.",
        "Altura": "1-2 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Média",
        "Crescimento": "Moderado",
        "Solo Ideal": "Levemente ácido, bem drenado",
        "Floração": "Ano todo",
        "Cores": "Vermelho",
        "Tags": "Arbusto; Fácil de Cuidar; Tropical; Floração Ornamental; Cerca Viva; Atrai Borboletas"
    },
    {
        "Nome": "Dracena-tricolor",
        "Nome Científico": "Dracaena marginata 'Tricolor'",
        "Descrição": "Planta escultural com folhas finas e longas, marginadas de rosa e creme. Muito resistente e adapta-se bem a interiores ou exteriores.",
        "Altura": "2-4 m",
        "Luz Solar": "Meia Sombra",
        "Necessidade de Água": "Baixa",
        "Crescimento": "Lento",
        "Solo Ideal": "Bem drenado",
        "Floração": "Rara",
        "Cores": "Verde; Rosa; Creme",
        "Tags": "Arbusto; Fácil de Cuidar; Tropical; Folhagem Ornamental; Ideal para Vasos; Purifica o Ar; Resistente à Seca"
    },
    {
        "Nome": "Clúsia",
        "Nome Científico": "Clusia fluminensis",
        "Descrição": "Arbusto nativo brasiliero de folhas grossas e brilhantes. Excelente para cercas vivas.",
        "Altura": "2-4 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Baixa",
        "Crescimento": "Moderado",
        "Solo Ideal": "Variado, tolera solos pobres",
        "Floração": "Primavera",
        "Cores": "Verde; Branco",
        "Tags": "Arbusto; Fácil de Cuidar; Tropical; Tolerante à Maresia; Nativa do Brasil; Alta Resistência"
    },
    {
        "Nome": "Jequitibá-rosa",
        "Nome Científico": "Cariniana legalis",
        "Descrição": "Árvore majestosa e símbolo da Mata Atlântica. Uma das maiores árvores brasileiras, pode viver centenas de anos. O nome 'Jequitibá' vem do tupi e significa 'gigante da floresta'.",
        "Altura": "30-50 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Média",
        "Crescimento": "Lento",
        "Solo Ideal": "Fértil, profundo e bem drenado",
        "Floração": "Primavera e Verão",
        "Cores": "Verde; Branco",
        "Tags": "Árvore; Cuidado Moderado; Tropical; Nativa do Brasil; Sombra Densa; Reflorestamento; Gigante"
    },
    {
        "Nome": "Manacá-da-serra",
        "Nome Científico": "Pleroma raddianum",
        "Descrição": "Árvore que é um show de cores! Suas flores abrem brancas, tornam-se rosa e morrem roxas, criando um degradê espetacular na mesma planta.",
        "Altura": "3-6 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Média",
        "Crescimento": "Rápido",
        "Solo Ideal": "Rico em matéria orgânica",
        "Floração": "Verão",
        "Cores": "Branco; Rosa; Roxo",
        "Tags": "Árvore; Fácil de Cuidar; Tropical; Nativa do Brasil; Floração Ornamental; Crescimento Rápido"
    },
    {
        "Nome": "Samambaia-americana",
        "Nome Científico": "Nephrolepis exaltata",
        "Descrição": "Clássica planta pendente, com folhas longas e arqueadas. Adora a umidade do ar de Ilhéus e é perfeita para varandas e áreas internas bem iluminadas.",
        "Altura": "0.5-1 m (pendente)",
        "Luz Solar": "Meia Sombra",
        "Necessidade de Água": "Alta",
        "Crescimento": "Rápido",
        "Solo Ideal": "Rico em matéria orgânica, bem drenado",
        "Floração": "Não se aplica",
        "Cores": "Verde",
        "Tags": "Herbácea; Fácil de Cuidar; Tropical; Folhagem Ornamental; Ideal para Vasos; Tolerante à Sombra; Purifica o Ar; Umidade Alta"
    },
    {
        "Nome": "Palmeira-areca",
        "Nome Científico": "Dypsis lutescens",
        "Descrição": "Uma das palmeiras mais populares. Forma touceiras densas com troncos finos e amarelados. Ótima para criar barreiras visuais ou como planta de interior.",
        "Altura": "3-6 m",
        "Luz Solar": "Meia Sombra",
        "Necessidade de Água": "Média",
        "Crescimento": "Moderado",
        "Solo Ideal": "Rico em matéria orgânica, bem drenado",
        "Floração": "Verão",
        "Cores": "Verde; Amarelo",
        "Tags": "Palmeira; Fácil de Cuidar; Tropical; Folhagem Ornamental; Ideal para Vasos; Purifica o Ar; Cerca Viva"
    },
    {
        "Nome": "Jabuticabeira",
        "Nome Científico": "Myrciaria cauliflora",
        "Descrição": "Árvore frutífera nativa que produz frutos deliciosos direto no tronco e galhos. Um ícone de pomares brasileiros.",
        "Altura": "4-8 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Alta",
        "Crescimento": "Lento",
        "Solo Ideal": "Fértil e úmido",
        "Floração": "Primavera e Verão",
        "Cores": "Branco; Roxo",
        "Tags": "Árvore; Cuidado Moderado; Tropical; Frutífera; Nativa do Brasil; Atrai Pássaros; Tronco Ornamental"
    },
    {
        "Nome": "Agave-dragão",
        "Nome Científico": "Agave attenuata",
        "Descrição": "Planta suculenta escultural com folhas macias, verde-claras, que formam uma roseta perfeita. Não possui espinhos agressivos como outras agaves.",
        "Altura": "1-1.5 m",
        "Luz Solar": "Meia Sombra",
        "Necessidade de Água": "Baixa",
        "Crescimento": "Lento",
        "Solo Ideal": "Bem drenado, arenoso",
        "Floração": "Rara (após muitos anos)",
        "Cores": "Verde-azulado",
        "Tags": "Suculenta; Fácil de Cuidar; Tropical; Folhagem Ornamental; Resistente à Seca; Ideal para Vasos"
    },
    {
        "Nome": "Abacaxi-roxo",
        "Nome Científico": "Tradescantia spathacea",
        "Descrição": "Planta rasteira extremamente resistente, com folhas em tons de verde e roxo. Usada para cobrir o solo em áreas de sombra ou meia sombra.",
        "Altura": "0.2-0.4 m",
        "Luz Solar": "Meia Sombra",
        "Necessidade de Água": "Baixa",
        "Crescimento": "Rápido",
        "Solo Ideal": "Variado, bem drenado",
        "Floração": "Ano todo (discreta)",
        "Cores": "Verde; Roxo",
        "Tags": "Herbácea; Fácil de Cuidar; Tropical; Folhagem Ornamental; Forração; Alta Resistência"
    },
    {
        "Nome": "Primavera",
        "Nome Científico": "Bougainvillea glabra",
        "Descrição": "A rainha das trepadeiras coloridas. Suas brácteas (folhas modificadas) em tons vibrantes de rosa, roxo ou laranja cobrem a planta de cor.",
        "Altura": "5-10 m (apoiada)",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Baixa",
        "Crescimento": "Rápido",
        "Solo Ideal": "Bem drenado",
        "Floração": "Primavera e Verão",
        "Cores": "Rosa; Roxo; Laranja; Branco",
        "Tags": "Trepadeira; Fácil de Cuidar; Tropical; Floração Ornamental; Resistente à Seca; Cerca Viva"
    },
    {
        "Nome": "Zamioculca",
        "Nome Científico": "Zamioculcas zamiifolia",
        "Descrição": "A 'planta da fortuna' é quase indestrutível. Folhas verdes brilhantes e grossas, tolera pouca luz e esquecimento de regas. Perfeita para iniciantes.",
        "Altura": "0.5-1 m",
        "Luz Solar": "Sombra",
        "Necessidade de Água": "Baixa",
        "Crescimento": "Lento",
        "Solo Ideal": "Bem drenado",
        "Floração": "Rara (sem importância ornamental)",
        "Cores": "Verde",
        "Tags": "Herbácea; Fácil de Cuidar; Tropical; Folhagem Ornamental; Tolerante à Sombra; Purifica o Ar; Resistente à Seca; Ideal para Vasos"
    },
    {
        "Nome": "Açucena-branca",
        "Nome Científico": "Hippeastrum 'Arctic Nymph'",
        "Descrição": "Bulbo que produz flores espetaculares, brancas e enormes. Desaparece após a floração e retorna no ano seguinte.",
        "Altura": "0.4-0.6 m",
        "Luz Solar": "Meia Sombra",
        "Necessidade de Água": "Média",
        "Crescimento": "Rápido (na estação)",
        "Solo Ideal": "Rico em matéria orgânica, bem drenado",
        "Floração": "Inverno e Primavera",
        "Cores": "Branco",
        "Tags": "Bulbo; Cuidado Moderado; Tropical; Floração Ornamental; Ideal para Vasos"
    },
    {
        "Nome": "Moreia-branca",
        "Nome Científico": "Dietes iridioides",
        "Descrição": "Planta herbácea muito resistente, com folhagem fina e ereta. Produz flores brancas delicadas que parecem íris, quase o ano todo.",
        "Altura": "0.6-1 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Baixa",
        "Crescimento": "Rápido",
        "Solo Ideal": "Variado, tolera solos pobres",
        "Floração": "Ano todo (picos na Primavera/Verão)",
        "Cores": "Branco; Amarelo; Roxo",
        "Tags": "Herbácea; Fácil de Cuidar; Tropical; Floração Ornamental; Alta Resistência; Bordadura"
    },
    {
        "Nome": "Lírio-da-paz",
        "Nome Científico": "Spathiphyllum wallisii",
        "Descrição": "Famosa por purificar o ar e tolerar pouca luz. Suas 'flores' brancas são na verdade brácteas que envolvem as flores reais. Aviso: é tóxica para pets.",
        "Altura": "0.4-0.6 m",
        "Luz Solar": "Sombra",
        "Necessidade de Água": "Alta",
        "Crescimento": "Moderado",
        "Solo Ideal": "Rico em matéria orgânica, úmido",
        "Floração": "Ano todo (picos na Primavera)",
        "Cores": "Branco; Verde",
        "Tags": "Herbácea; Fácil de Cuidar; Tropical; Floração Ornamental; Tolerante à Sombra; Purifica o Ar; Umidade Alta; Tóxica para Pets"
    },
    {
        "Nome": "Grampe-amendoim",
        "Nome Científico": "Arachis repens",
        "Descrição": "Excelente cobertura de solo (forração). Cresce rápido, sufoca o mato e produz pequenas flores amarelas. Muito resistente ao sol e pisoteio.",
        "Altura": "0.1-0.2 m (rasteira)",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Média",
        "Crescimento": "Rápido",
        "Solo Ideal": "Variado",
        "Floração": "Ano todo",
        "Cores": "Amarelo; Verde",
        "Tags": "Forração; Fácil de Cuidar; Tropical; Tolerante à Maresia; Resistente ao Pisoteio"
    },
    {
        "Nome": "Jasmim-Manga",
        "Nome Científico": "Plumeria rubra",
        "Descrição": "Árvore pequena de flores perfumadas e coloridas. Símbolo dos trópicos com aroma inconfundível.",
        "Altura": "3-5 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Baixa",
        "Crescimento": "Lento",
        "Solo Ideal": "Bem drenado",
        "Floração": "Primavera e Verão",
        "Cores": "Branco; Rosa; Amarelo",
        "Tags": "Árvore; Fácil de Cuidar; Tropical; Tolerante à Maresia; Flores Perfumadas; Resistente à Seca"
    },
    {
        "Nome": "Antúrio Vermelho",
        "Nome Científico": "Anthurium andraeanum",
        "Descrição": "Planta de flores vermelhas brilhantes que duram semanas. Perfeita para áreas sombreadas.",
        "Altura": "0.4-0.6 m",
        "Luz Solar": "Meia Sombra",
        "Necessidade de Água": "Média",
        "Crescimento": "Lento",
        "Solo Ideal": "Rico em matéria orgânica, bem drenado",
        "Floração": "Ano todo",
        "Cores": "Vermelho",
        "Tags": "Herbácea; Cuidado Moderado; Tropical; Floração Ornamental; Ideal para Vasos; Tolerante à Sombra; Umidade Alta"
    },
    {
        "Nome": "Açaí-juçara",
        "Nome Científico": "Euterpe edulis",
        "Descrição": "A palmeira nativa da Mata Atlântica que produz o açaí. Famosa pelo 'palmito juçara' e seus frutos roxos nutritivos. Essencial para a fauna local.",
        "Altura": "10-15 m",
        "Luz Solar": "Meia Sombra",
        "Necessidade de Água": "Alta",
        "Crescimento": "Moderado",
        "Solo Ideal": "Fértil e úmido",
        "Floração": "Primavera",
        "Cores": "Branco; Roxo",
        "Tags": "Árvore; Fácil de Cuidar; Tropical; Frutífera; Atrai Pássaros; Sombra Densa; Nativa do Brasil"
    },
    {
        "Nome": "Araçá-amarelo",
        "Nome Científico": "Psidium cattleianum",
        "Descrição": "O 'mini goiabão' da Mata Atlântica! Produz frutos amarelos deliciosos, muito procurados por pássaros. É parente da goiaba e tem sabor igualmente doce e aromático.",
        "Altura": "3-5 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Média",
        "Crescimento": "Moderado",
        "Solo Ideal": "Fértil",
        "Floração": "Primavera",
        "Cores": "Branco; Amarelo",
        "Tags": "Arbusto; Fácil de Cuidar; Tropical; Frutífera; Atrai Pássaros; Nativa do Brasil"
    },
    {
        "Nome": "Feijão-de-praia",
        "Nome Científico": "Canavalia rosea",
        "Descrição": "Planta rasteira nativa das praias de Ilhéus. Super resistente ao sol, vento e maresia. Suas flores são rosa/roxas e ela ajuda a segurar a areia.",
        "Altura": "0.1-0.3 m (rasteira)",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Baixa",
        "Crescimento": "Rápido",
        "Solo Ideal": "Arenoso",
        "Floração": "Ano todo",
        "Cores": "Rosa; Roxo",
        "Tags": "Forração; Fácil de Cuidar; Tropical; Nativa do Brasil; Tolerante à Maresia; Resistente à Seca; Fixadora de Dunas"
    },
    {
        "Nome": "Pau-brasil",
        "Nome Científico": "Paubrasilia echinata",
        "Descrição": "A árvore que deu nome ao nosso país. Nativa da Mata Atlântica, quase foi extinta pelo valor de sua madeira vermelha ('brasa'). Produz flores amarelas perfumadas.",
        "Altura": "10-15 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Média",
        "Crescimento": "Lento",
        "Solo Ideal": "Fértil, bem drenado",
        "Floração": "Primavera",
        "Cores": "Amarelo; Laranja",
        "Tags": "Árvore; Cuidado Moderado; Tropical; Tolerante à Maresia; Símbolo do Brasil; Uso de Madeira; Ameaçada de Extinção; Flores Perfumadas; Nativa do Brasil"
    },
    {
        "Nome": "Guapuruvu",
        "Nome Científico": "Schizolobium parahyba",
        "Descrição": "Conhecida como 'fósforo vegetal', tem o crescimento mais rápido entre as árvores nativas! Pode crescer até 3 metros por ano. Suas flores amarelas formam um espetáculo dourado.",
        "Altura": "20-30 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Alta",
        "Crescimento": "Rápido",
        "Solo Ideal": "Fértil e úmido",
        "Floração": "Primavera",
        "Cores": "Amarelo",
        "Tags": "Árvore; Fácil de Cuidar; Tropical; Crescimento Rápido; Reflorestamento; Floração Ornamental; Uso de Madeira; Nativa do Brasil"
    },
    {
        "Nome": "Quaresmeira",
        "Nome Científico": "Pleroma granulosum",
        "Descrição": "Recebe esse nome porque floresce na época da Quaresma. É uma das árváores nativas de floração roxa mais espetaculares do Brasil. Muito ornamental.",
        "Altura": "8-12 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Média",
        "Crescimento": "Moderado",
        "Solo Ideal": "Fértil e úmido",
        "Floração": "Outono e Inverno",
        "Cores": "Roxo",
        "Tags": "Árvore; Fácil de Cuidar; Tropical; Nativa do Brasil; Floração Ornamental"
    },
    {
        "Nome": "Caju",
        "Nome Científico": "Anacardium occidentale",
        "Descrição": "Árvore nativa do litoral, famosa pelo pseudofruto (o caju) e pela castanha. Extremamente adaptada ao clima quente e solos arenosos de Ilhéus.",
        "Altura": "5-10 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Baixa",
        "Crescimento": "Rápido",
        "Solo Ideal": "Diversos tipos, bem adaptável",
        "Floração": "Primavera e Verão",
        "Cores": "Branco; Vermelho",
        "Tags": "Árvore; Fácil de Cuidar; Tropical; Tolerante à Maresia; Frutífera; Alta Resistência; Atrai Pássaros; Uso Medicinal; Nativa do Brasil"
    },
    {
        "Nome": "Paineira-rosa",
        "Nome Científico": "Ceiba speciosa",
        "Descrição": "Árvore icônica com tronco cheio de espinhos quando jovem e flores rosa espetaculares. Seus frutos soltam uma 'paina' sedosa que era usada para rechear travesseiros - daí o nome!",
        "Altura": "20-30 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Baixa",
        "Crescimento": "Rápido",
        "Solo Ideal": "Bem drenado",
        "Floração": "Outono (após perder as folhas)",
        "Cores": "Rosa; Branco",
        "Tags": "Árvore; Fácil de Cuidar; Tropical; Tronco Ornamental; Floração Ornamental; Fibra Natural; Decídua; Nativa do Brasil"
    },
    {
        "Nome": "Bromélia-imperial",
        "Nome Científico": "Alcantarea imperialis",
        "Descrição": "Bromélia gigante nativa do Brasil, pode atingir mais de 1,5m de diâmetro. Antes de morrer (após anos), solta uma haste floral espetacular que chega a 3m de altura.",
        "Altura": "1-1.5 m (folhas)",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Baixa",
        "Crescimento": "Lento",
        "Solo Ideal": "Bem drenado, pode ser arenoso",
        "Floração": "Verão",
        "Cores": "Amarelo; Laranja; Roxo",
        "Tags": "Herbácea; Fácil de Cuidar; Tropical; Nativa do Brasil; Tolerante à Maresia; Tolerante à Seca; Folhagem Ornamental; Ideal para Vasos"
    },
    {
        "Nome": "Maranta Tricolor",
        "Nome Científico": "Maranta leuconeura var. erythroneura",
        "Descrição": "Nativa do chão da floresta com padrões de folhas incríveis! Mas é sensível a tudo: sol direto queima, ar seco deixa as bordas marrons, rega errada causa problemas. Precisa recriar o 'bafo quente e úmido' da mata - um verdadeiro desafio fora do ambiente natural.",
        "Altura": "0.3-0.5 m",
        "Luz Solar": "Sombra",
        "Necessidade de Água": "Alta",
        "Crescimento": "Moderado",
        "Solo Ideal": "Rico em matéria orgânica, sempre levemente úmido",
        "Floração": "Primavera",
        "Cores": "Verde; Vermelho; Creme",
        "Tags": "Herbácea; Difícil de Cuidar; Tropical; Folhagem Ornamental; Movimento Noturno; Ideal para Vasos; Nativa do Brasil"
    },
    {
        "Nome": "Orquídea Cattleya",
        "Nome Científico": "Cattleya labiata",
        "Descrição": "A 'Rainha das Orquídeas' e flor nacional do Brasil. Nativa da Mata Atlântica. É uma planta epífita (vive sobre árvores) que ama a umidade do ar, mas detesta raízes encharcadas. Requer cuidados específicos com rega e luz.",
        "Altura": "0.3-0.5 m",
        "Luz Solar": "Meia Sombra",
        "Necessidade de Água": "Média",
        "Crescimento": "Lento",
        "Solo Ideal": "Substrato para epífitas (casca de pinus, carvão)",
        "Floração": "Outono",
        "Cores": "Rosa; Roxo; Branco",
        "Tags": "Orquídea; Difícil de Cuidar; Tropical; Nativa do Brasil; Floração Ornamental; Flores Perfumadas; Epífita"
    },
    {
        "Nome": "Alfinete-de-sol",
        "Nome Científico": "Asclepias curassavica",
        "Descrição": "Pequena planta nativa que é um imã para borboletas, especialmente a Monarca. Produz cachos de flores vibrantes em laranja e vermelho. Planta de restinga e muito resistente.",
        "Altura": "0.3-0.6 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Baixa",
        "Crescimento": "Lento",
        "Solo Ideal": "Arenoso, bem drenado",
        "Floração": "Primavera e Verão",
        "Cores": "Laranja; Vermelho",
        "Tags": "Herbácea; Fácil de Cuidar; Tropical; Nativa do Brasil; Tolerante à Maresia; Floração Ornamental"
    },
    {
        "Nome": "Maranta-pavão",
        "Nome Científico": "Maranta leuconeura var. kerchoveana",
        "Descrição": "Nativa do sub-bosque (Mata Atlântica). Conhecida pelas folhas ovais verde-claras com manchas escuras (verde-oliva ou marrom) que lembram penas de pavão. As folhas se fecham à noite (movimento noturno).",
        "Altura": "0.3-0.5 m",
        "Luz Solar": "Sombra",
        "Necessidade de Água": "Alta",
        "Crescimento": "Moderado",
        "Solo Ideal": "Rico em matéria orgânica, bem drenado",
        "Floração": "Primavera",
        "Cores": "Verde; Branco",
        "Tags": "Herbácea; Difícil de Cuidar; Tropical; Folhagem Ornamental; Movimento Noturno; Tolerante à Sombra; Ideal para Vasos; Nativa do Brasil"
    },
    {
        "Nome": "Ipê-roxo",
        "Nome Científico": "Handroanthus impetiginosus",
        "Descrição": "Árvore símbolo ornamental. Famoso por sua floração espetacular em tons de rosa-escuro (magenta), que ocorre no inverno, antes do surgimento das folhas. Muito usado na arborização urbana.",
        "Altura": "8-12 m",
        "Luz Solar": "Sol Pleno",
        "Necessidade de Água": "Baixa",
        "Crescimento": "Lento",
        "Solo Ideal": "Bem drenado",
        "Floração": "Inverno",
        "Cores": "Roxo; Rosa",
        "Tags": "Árvore; Fácil de Cuidar; Tropical; Floração Ornamental; Decídua; Nativa do Brasil"
    }
];